### PR TITLE
HS3 arduino pcb

### PR DESCRIPTION
**Pull request by lukasz-tuz**
Pull request adds designs for two custom boards in Arduino form factor:

* hs3-arduino: Arduino Uno form factor with ESP32 (design not finished)
* hs3-arduino-nano: Arduino Nano form factor with RP2040 (completed routing)

Nano board has dual pin headers with ground and +3.3V for powering external sensors and two DF13 headers for GPIO signals. One is meant for I2C connectivity, but its all GPIOs.

Power is supplied by either USB micro or a dedicated connector. Input voltage range is 4.5 - 12V (personally wouldn't exceed 9V).

### CODE REVIEW

**Review by DoomHammer — APPROVED** [review]
I have no idea what you did there, but I like the pics!

**Comment by lukasz-tuz** [comment]
> I have no idea what you did there, but I like the pics!

Thanks 😆 FYI, this PR still needs a couple of updates to the PCB design (work in progress) and creation of BOM and manufacturing files.

**Comment by lukasz-tuz** [comment]
Aaand done :)

**Comment by DoomHammer** [comment]
Are we merging this beauty?

**Comment by lukasz-tuz** [comment]
> Are we merging this beauty?

It's ready to merge on my end. I don't have write access, so can't do it myself :)

**Pull request merged**
